apiVersion: v1
kind: Service
metadata:
  name: jboss-rsyslog-0
spec:
  selector:
    app: jboss-rsyslog-0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jboss-rsyslog-1
spec:
  selector:
    app: jboss-rsyslog-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080