#FROM registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.18-3.1724180403
FROM jboss-eap-7/eap74-openjdk11-openshift-rhel8:7.4.18-3.1724180403

COPY hello-world-app/target/jboss-rsyslog.war /opt/eap/standalone/deployments/