FROM registry.access.redhat.com/ubi8/openjdk-11-runtime:1.20-2.1727147566

USER root
RUN microdnf install nc;

COPY hello-world-app/jboss-eap-74/ /opt/jboss-eap-74
COPY hello-world-app/target/jboss-rsyslog.war /opt/jboss-eap-74/standalone/deployments/jboss-rsyslog.war
COPY hello-world-app/src/main/eap/start-and-config-eap.sh /home/jboss/start-and-config-eap.sh

RUN chmod 766 /opt/jboss-eap-74/standalone/data/content
RUN chmod 766 /opt/jboss-eap-74/standalone/tmp
RUN chown jboss:jboss /opt/jboss-eap-74/standalone
RUN chmod +x /home/jboss/start-and-config-eap.sh

RUN chgrp -R 0 /opt/jboss-eap-74 && \
    chmod -R g+rwX /opt/jboss-eap-74

USER 1001

CMD /home/jboss/start-and-config-eap.sh