apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: rsyslog-server-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: quayconfig
  params:
    - description: url of the git repo for the code of deployment
      name: git-url
      type: string
      default: https://github.com/marcoklaassen/jboss-eap-rsyslog.git
    - description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
      default: main
    - description: image to be built from the code
      name: IMAGE
      type: string
      default: quay.io/mklaasse/rsyslog-server:latest
    - description: dockerfile location
      name: DOCKERFILE
      type: string
      default: hello-world-app/src/main/docker/Containerfile.rsyslog
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.IMAGE)
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: quayconfig